manifest:
  remotes:
    # old
    # - name: urob
    #   url-base: https://github.com/urob/
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    ## old
    # - name: zmk
    #  remote: urob
    #  revision: main
    #  import: app/west.yml
    # - name: zmk-helpers
    #  remote: urob
    #  revision: main
    - name: zmk
      remote: zmk
      revision: main
      import: app/west.yml
  self:
    path: config
# update 250720 
# https://zmk.dev/docs/keymaps/behaviors/mouse-emulation 
